[package]
name = "InteractiveStorefront"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.17.2", features = ["jpeg"] }
avian3d = "0.4"
bevy-tokio-tasks = "0.16.0"
tokio = { version = "1.37", features = ["macros", "rt-multi-thread"] }
serde = { version = "1", default-features = false, features = ["derive"] }
serde_json = "1"
